// <auto-generated />
namespace FakeEstate.ListingManager.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class AllowCommercialListings : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AllowCommercialListings));
        
        string IMigrationMetadata.Id
        {
            get { return "201407111910172_AllowCommercialListings"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
